-- Tracks
INSERT INTO tracks (title, description, icon) VALUES ('أساسيات الأمن السيبراني', 'مسار شامل لتعلم أساسيات الأمن السيبراني والشبكات', 'ShieldCore');
INSERT INTO courses (track_id, title, description) VALUES (last_insert_rowid(), 'مقدمة في الأمن السيبراني', 'تعرف على المفاهيم الأساسية للأمن وحماية البيانات');
INSERT INTO units (course_id, title) VALUES (last_insert_rowid(), 'الوحدة الأولى: المفاهيم الأساسية ولينكس');
INSERT INTO lessons (unit_id, title, content, terminal_config, quiz_config, is_interactive, xp_reward) VALUES (last_insert_rowid(), 'درس 1: أوامر لينكس الأساسية', 'في هذا الدرس سنتعلم الأوامر الأساسية في نظام تشغيل لينكس للتعامل مع الملفات والمجلدات.', '{"type":"bash_simulator","tasks":[{"title":"عرض محتويات الدليل","description":"استخدم الأمر ls لعرض الملفات","command":"ls","expectedOutput":"file1.txt"}],"fileSystem":{"/home/user":{"type":"dir","children":{"file1.txt":{"type":"file","content":"test content"}}}}}', '[{"question":"ما هو الأمر المستخدم لعرض محتويات الدليل في لينكس؟","options":["cd","ls","pwd","mkdir"],"correctOption":1}]', 1, 50);

INSERT INTO tracks (title, description, icon) VALUES ('اختبار الاختراق', 'مسار متقدم لتعلم تقنيات وأدوات اختبار الاختراق الأخلاقي', 'Sword');
INSERT INTO courses (track_id, title, description) VALUES (last_insert_rowid(), 'أساسيات اختبار الاختراق', 'دورة تركز على جمع المعلومات وفحص الثغرات');
INSERT INTO units (course_id, title) VALUES (last_insert_rowid(), 'الوحدة الأولى: جمع المعلومات');
INSERT INTO lessons (unit_id, title, content, terminal_config, quiz_config, is_interactive, xp_reward) VALUES (last_insert_rowid(), 'درس 1: استكشاف الشبكة وأنظمة التشغيل', 'تعرف على أساسيات الشبكات وكيفية التعامل مع موجه الأوامر لاكتشاف المنافذ.', '{"type":"bash_simulator","tasks":[{"title":"معرفة مسار الدليل الحالي","description":"استخدم الأمر pwd لمعرفة المسار","command":"pwd","expectedOutput":"/home/user"}],"fileSystem":{"/home/user":{"type":"dir","children":{}}}}', '[{"question":"أي من الأوامر التالية يستخدم لتغيير الدليل؟","options":["cd","ls","pwd","rm"],"correctOption":0}]', 1, 50);

INSERT INTO tracks (title, description, icon) VALUES ('التحقيق الجنائي الرقمي', 'مسار متخصص في تحليل الأدلة الرقمية والتحقيق في الحوادث', 'Search');
INSERT INTO courses (track_id, title, description) VALUES (last_insert_rowid(), 'التحقيق الجنائي للحواسيب', 'دورة توفر المهارات اللازمة للتحليل الجنائي');
INSERT INTO units (course_id, title) VALUES (last_insert_rowid(), 'الوحدة الأولى: تحليل الأدلة');
INSERT INTO lessons (unit_id, title, content, terminal_config, quiz_config, is_interactive, xp_reward) VALUES (last_insert_rowid(), 'درس 1: استخراج الملفات المخفية', 'تعلم كيفية استرجاع واستخراج البيانات المخفية باستخدام سطر الأوامر.', '{"type":"bash_simulator","tasks":[{"title":"إنشاء ملف جديد","description":"استخدم الأمر touch لإنشاء ملف باسم test.txt","command":"touch test.txt","expectedOutput":""}],"fileSystem":{"/home/user":{"type":"dir","children":{}}}}', '[{"question":"الأمر touch يستخدم لـ:","options":["إنشاء مجلد","عرض الملفات","إنشاء ملف فارغ","نسخ الملفات"],"correctOption":2}]', 1, 50);

-- News
INSERT INTO news (title, body, tags, type, image_url) VALUES ('اكتشاف ثغرة خطيرة في بروتوكول WPA3', 'اكتشف باحثون ثغرة جديدة في بروتوكول WPA3 للشبكات اللاسلكية تسمح باعتراض البيانات.', '["ثغرات", "شبكات"]', 'news', '/assets/news/1.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('هجوم سيبراني يستهدف خوادم مايكروسوفت إكستشينج', 'تعرضت العديد من المؤسسات لاختراقات بسبب سلسلة عيوب في خوادم البريد مايكروسوفت.', '["اختراق", "هجمات"]', 'news', '/assets/news/2.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('إطلاق أداة جديدة مفتوحة المصدر لتحليل البرمجيات الخبيثة', 'قام فريق أمني بإطلاق أداة جديدة تساعد المحللين في تفكيك البرمجيات الرانسوموير.', '["أدوات", "برمجيات خبيثة"]', 'news', '/assets/news/3.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('تحذير من هجمات التصيد الاحتيالي باستخدام تقنية Deepfake', 'أصدر الخبراء تحذيراً من تزايد استخدام التزييف العميق لخداع الموظفين في الشركات الكبرى.', '["تزييف عميق", "تصيد"]', 'news', '/assets/news/4.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('شركة أمن سيبراني سعودية تعلن عن تمويل جديد', 'أعلنت إحدى الشركات الناشئة في مجال الأمن السيبراني في المملكة عن جولة تمويلية بأكثر من مليار ريال.', '["استثمار", "السعودية"]', 'news', '/assets/news/5.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('ارتفاع حوادث برمجيات الفدية بنسبة 30% خلال الربع الأخير', 'أظهر تقرير جديد زيادة ملحوظة في هجمات المطالبة بالفدية في قطاعات الرعاية الصحية والتعليم.', '["فدية", "إحصائيات"]', 'news', '/assets/news/6.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('الكشف عن تسريب بيانات لأكثر من مليون مستخدم بتطبيق شهير', 'تم رصد قاعدة بيانات على الإنترنت المظلم تحتوي على أسماء وأرقام هواتف لمستخدمين في تطبيق المراسلات.', '["تسريب", "بيانات"]', 'news', '/assets/news/7.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('تحديث أمني عاجل لأنظمة أبل لمعالجة ثغرة زيرو داي', 'أطلقت شركة أبل تحديثاً جديداً لسد ثغرة خطيرة قد تسمح بالتحكم الكامل بالأجهزة.', '["أبل", "تحديثات"]', 'news', '/assets/news/8.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('اعتقال مجموعة قراصنة مسؤولة عن هجمات طلب الفدية', 'أعلنت الشرطة الدولية (الإنتربول) عن تفكيك عصابة سيبرانية بعد تحقيقات استمرت لعام.', '["قانون", "جرائم سيبرانية"]', 'news', '/assets/news/9.jpg');
INSERT INTO news (title, body, tags, type, image_url) VALUES ('إصدار التقرير السنوي للتهديدات السيبرانية', 'أصدر المركز الوطني للأمن السيبراني التقرير السنوي الذي يوضح أبرز التوجهات الأمنية للعام الجاري.', '["تقارير", "وعي أمني"]', 'news', '/assets/news/10.jpg');

-- Articles
INSERT INTO articles (title, content, author, tags) VALUES ('دليلك الشامل لتعلم أساسيات الأمن السيبراني', 'في هذه المقالة، سنستعرض الخطوات الأساسية التي يجب على كل مبتدئ اتباعها لتعلم الأمن السيبراني بنجاح وتأسيس معرفة قوية.', 'أحمد محمد', '["مبتدئين", "دليل"]');
INSERT INTO articles (title, content, author, tags) VALUES ('أهمية التشفير في حماية البيانات الخاصة', 'التشفير هو حجر الزاوية في الحفاظ على خصوصيتنا عبر الإنترنت. يناقش المقال تقنيات التشفير الحديثة وطرق عملها.', 'فاطمة السعيد', '["تشفير", "خصوصية"]');
INSERT INTO articles (title, content, author, tags) VALUES ('كيف تتجنب أساليب الهندسة الاجتماعية والمخادعين المهرة', 'الهندسة الاجتماعية تعتمد على التلاعب النفسي. سنتعلم كيفية التعرف على رسائل المتصيدين والحيل التي يمكن أن تورطك.', 'عمر القحطاني', '["هندسة اجتماعية", "توعية"]');
INSERT INTO articles (title, content, author, tags) VALUES ('نظرة معمقة في تحليل البرمجيات الخبيثة وتفكيك الكود', 'تحليل الفيروسات والتروجانات يتطلب بيئات معزولة وأدوات احترافية، نلقي نظرة على منهجيات المحللين.', 'ياسر خالد', '["برمجيات خبيثة", "هندسة عكسية"]');
INSERT INTO articles (title, content, author, tags) VALUES ('حماية شبكات الواي فاي المنزلية بخطوات عملية بسيطة', 'شبكات الواي فاي غير المحمية تعتبر باباً مفتوحاً للقراصنة، نشرح في هذا الدليل خطوات تأمين الشبكة وإغلاق الثغرات.', 'ريم عبد العزيز', '["شبكات", "واي فاي", "حماية"]');
INSERT INTO articles (title, content, author, tags) VALUES ('مستقبل الذكاء الاصطناعي في الدفاع السيبراني', 'كيف يساهم الذكاء الاصطناعي في كشف التهديدات بسرعة، وهل سيرجح كفة المدافعين أم المهاجمين في المستقبل؟', 'د. سامي العتيبي', '["ذكاء اصطناعي", "مستقبل"]');
INSERT INTO articles (title, content, author, tags) VALUES ('أدوات اختبار الاختراق التي لا غنى عنها لكل هاكر أخلاقي', 'من الميتاسبلويت إلى الإن ماب، هذه المقالة تسرد أهم الأدوات وتطبيقاتها في اختبار قوة وأمان الأنظمة المعاصرة.', 'سالم الدوسري', '["أدوات", "اختبار اختراق"]');
INSERT INTO articles (title, content, author, tags) VALUES ('فهم هجمات حجب الخدمة الموزعة وكيفية التخفيف منها', 'نظرة تقنية حول آليات عمل هجمات DDoS والطرق الفعّالة لحماية البنية التحتية والخوادم منها.', 'محمد العمري', '["DDoS", "هجمات شبكات"]');
INSERT INTO articles (title, content, author, tags) VALUES ('التحقيق الرقمي بعد حدوث اختراق أمني داخل الشركة', 'ما هي أول الخطوات التي يجب اتخاذها عندما يتم الكشف عن اختراق؟ مقال يشرح خطة الاستجابة السريعة.', 'نورة الحسن', '["استجابة حوادث", "تحقيق رقمي"]');
INSERT INTO articles (title, content, author, tags) VALUES ('كيف تختار نظام تشغيل آمن مناسب لعمليات الأمن السيبراني؟', 'مقارنة بين توزيعات لينكس المختلفة ككالي لينكس وباروت أمن ومزايا كل منها في توفير بيئة عمل آمنة ومريحة.', 'حسن الفايز', '["أنظمة تشغيل", "كالي", "لينكس"]');

-- Events
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('ورشة عمل حول التحليل الجنائي', 'workshop', 'training', '2026-03-01', '18:00', 'أونلاين عبر زووم', 'ورشة عملية شاملة تغطي أساسيات جمع الأدلة الرقمية.', '/assets/events/1.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('تحدي التقاط العلم الأول لعام 2026', 'competition', 'event', '2026-03-10', '10:00', 'جامعة طويق', 'مسابقة CTF ضخمة لتحدي قدرات الطلاب في مختلف التخصصات السيبرانية.', '/assets/events/2.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('ندوة عن الأمن السحابي وحماية البنية التحتية', 'seminar', 'seminar', '2026-03-15', '20:00', 'المسرح الرئيسي', 'محاضرة يقدمها خبراء حول كيفية تأمين البيانات والخدمات السحابية.', '/assets/events/3.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('دورة تأهيلية لشهادة سيسكو للشبكات السيبرانية', 'course', 'training', '2026-03-20', '17:00', 'مبنى الحاسبات', 'دورة مكثفة تغطي منهج شهادة CCNA وتطبيقاتها في أمان الشبكات.', '/assets/events/4.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('لقاء مفتوح مع خبراء الأمن السيبراني في سابك', 'meetup', 'talks', '2026-03-25', '19:00', 'قاعة المؤتمرات', 'جلسة حوارية مع مهندسين لمناقشة تحديات أمن المعلومات في القطاع الصناعي.', '/assets/events/5.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('معسكر تدريبي مكثف: الهاكر الأخلاقي المحترف', 'bootcamp', 'training', '2026-04-01', '09:00', 'قاعات التدريب المركزية', 'برنامج مكثف لمدة أسبوع لتجهيز المتدربين لاختراق الأنظمة برخصة أخلاقية.', '/assets/events/6.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('مسابقة محاكاة اختراق تطبيقات الويب', 'competition', 'event', '2026-04-10', '12:00', 'أونلاين - منصة النادي', 'تحدي عملي لايجاد ثغرات ويب وإبلاغ منصات Bug Bounty.', '/assets/events/7.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('استعراض أدوات استخبارات التهديدات مفتوحة المصدر (OSINT)', 'workshop', 'workshop', '2026-04-15', '16:00', 'معمل الأمن السيبراني', 'تعلم كيفية جمع المعلومات عن الأهداف المحتملة من المصادر المفتوحة.', '/assets/events/8.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('جلسة توعوية: حماية البيانات الشخصية والوعي الرقمي', 'seminar', 'seminar', '2026-04-20', '21:00', 'أونلاين', 'تثقيف عام للطلاب حول أهمية كلمات المرور القوية وتفعيل المصادقة الثنائية.', '/assets/events/9.jpg');
INSERT INTO club_events (title, type, category, date, time, location, description, image) VALUES ('مؤتمر نادي الأمن السيبراني السنوي المجمع', 'conference', 'conference', '2026-05-01', '09:00', 'فندق ماريوت', 'الحدث السنوي الأكبر للنادي لاستعراض إنجازات الأعضاء وتوزيع الجوائز.', '/assets/events/10.jpg');
